### ISSUE TITLE
Android: lost connection after a server restart

### ISSUE THREAD

**Issue by MatMaul** [binwiederhier/ntfy#100]
When restarting the server, my Android phone is silently loosing the connection.
Logs from the android app says the conn is alive but it's not. No subscribers in server logs and no messages is going down. Restarting the service by toggling the wakelock pref fixed it.
I haven't wait the 5mn timeout that would probably solve it, but it's longggg anyway :) 

I can reproduce it all the time.

**Comment by MatMaul** [comment]
Let's see if it's solved by some websocket magic :crossed_fingers: .

**Comment by MatMaul** [comment]
It was still not working after the 5mn timeout.
However websocket recovered pretty quickly (less than 10s) \o/

**Comment by binwiederhier** [comment]
Yeah sort of the reason why I want to switch to the websockets way is because I am incredibly unhappy with how I implemented the HTTP JSON stream. It should eventually recover, but it can take a little time. If the connection breaks it should be only a few seconds though. 

If the connection is just silently taken away (like apparently the Huawei phone from Jakob did), it has to wait up to 30s+5min, so quite the long time. 

If the 5min timeout is not working for you that's odd. I am not sure how much time I want to spend debugging it, since I want to switch to websockets anyway...

**Comment by MatMaul** [comment]
Yeah let's not bother and harden the ws one I would say.
