### ISSUE TITLE
[CLI] read topic, priority, etc from environment variables or config file

### ISSUE THREAD

**Issue by kzshantonu** [binwiederhier/ntfy#103]
If a topic, priority, etc is not specified when using `ntfy publish`, the CLI tool could read value from config file or environment. Could be handy for users who push to one topic most of the time

**Comment by binwiederhier** [comment]
The syntax for the publish command is this: `ntfy publish TOPIC [MESSAGE...]`, so you could write:

```
ntfy pub mytopic "my message"
ntfy pub mytopic my message
ntfy pub mytopic   # sends the message "triggered"
```

Since topic is the first argument, it's quite impossible to leave it blank, e.g. this:

```
ntfy pub "my message" 
```

would not work, because the first argument is the topic, not the message. The best I could do is this:

```
ntfy pub . "my message"  # where . means "use env"

# or this

ntfy pub -T "my message" # where -T means "use env"

```

but that's super ugly.

Thoughts?

**Comment by kzshantonu** [comment]
I guess dot is easier to type

**Comment by binwiederhier** [comment]
Implemented in https://github.com/binwiederhier/ntfy/commit/1552d8103e8c2f02677fa5c6f0a07a5f265b8085 as 

```
NTFY_TOPIC=mytopic ntfy pub -P "my message"
```
