### ISSUE TITLE
See you are enabled client also on Desktop but only android app 

### ISSUE THREAD

**Issue by jinfagang** [binwiederhier/ntfy#2]
Does it using flutter? What if I want a flutter as client?
So that we can cross platform get notifications.

**Comment by binwiederhier** [comment]
It does not use flutter. To my understanding flutter is a cross platform UI framework. You can already get notifications on Android and the desktop through the browser. So the only thing missing is iOS, right?

**Comment by jinfagang** [comment]
@binwiederhier  Yes, that's right.

**Comment by binwiederhier** [comment]
So I _think_ flutter would not work, because messaging stuff is pretty platform specific (web/Android/iOS). For instance, Android is very particular about not having background services and such, so I think that'd be tricky with an abstraction framework. So for now I'll stick with native. 

Plus, I don't have an iPhone anyway, so I'd have no way to test the app. I'm inviting you or anyone else to make an iOS app if you can :-D That'd be awesome.

**Comment by jinfagang** [comment]
@binwiederhier Flutter can also have background service implementation for receiving notifications.
