### ISSUE TITLE
Language selection function

### ISSUE THREAD

**Issue by MuratovAS** [binwiederhier/ntfy#214]
Good afternoon
Please add a manual language shift function in the settings. This applies to mobile application and web app.

**Comment by binwiederhier** [comment]
I thought this was gonna be easy, but apparently it is not, because `updateConfiguration` is deprecated: https://stackoverflow.com/questions/64400939/android-set-app-language-according-the-device-language

There is a way around it, but I don't really want to put this much effort into something that isn't in high demand. 

If you like this feature, please :+1: the initial post.

**Comment by MuratovAS** [comment]
I think it will be enough to add such a feature to the web application.
Many security browsers do not convey information about the language packs installed in the system. Most web applications have the ability to choose a language.

**Comment by binwiederhier** [comment]
The web app has a language selection drop-down already. It'll be in the next release.

**Comment by xmgz** [comment]
the dropdown selector lacks some of the already available languages. Browser, in web app interface, automatically selects my language (gl), but galician is not in the drop down list. 

in **android** app  language is **not** correctly loaded. Android language component is also [translated to galician](https://hosted.weblate.org/projects/ntfy/android/gl/), but it is not loaded. I don't know if this language is actually pulled in to the app from weblate.

thank you
