### ISSUE TITLE
Restoring topics or settings from backup doesn't work

### ISSUE THREAD

**Issue by shadow00** [binwiederhier/ntfy#223]
Just tried to backup and restore the topics and settings from the app (v1.11.0 from F-Droid) on an Android 8.1 device. The backup worked fine (even though the app didn't have storage permissions?), but restoring from backup doesn't work because the system's file picker doesn't allow selecting any file (even after giving the app the storage permission and making a new backup).

**Comment by binwiederhier** [comment]
Must be a problem with an older Android version. I'll check it out.

**Comment by binwiederhier** [comment]
I can reproduce this on a SDK 24 device. I hope there is an easy-ish solution:

![image](https://user-images.githubusercontent.com/664597/166160735-b2c99548-be1c-4d1e-845e-7955c9264164.png)

**Comment by binwiederhier** [comment]
solved in https://github.com/binwiederhier/ntfy-android/commit/400f72a9bf2f51bad34f4e1a77fe9d65c80b801c -- Will be in next release

**Comment by shadow00** [comment]
Well that was quick! :D

**Comment by binwiederhier** [comment]
For some bugs there are very pragmatic solutions. I think newer Android versions automatically detect the mime type, which is why it worked on newer versions. I can set the mime type on write, but then it's unclear what happens when you copy the backup file from somewhere else. So the pragmatic approach is to just allow selecting any file...
