### ISSUE TITLE
Messages with links not selectable

### ISSUE THREAD

**Issue by StoyanDimitrov** [binwiederhier/ntfy#226]
Messages with auto-linked text can not be selected by tap over the text, any text not only link. Tapping over empty area successfully selects message.

**Comment by binwiederhier** [comment]
Maybe this https://medium.com/@Saketme/a-better-way-to-handle-links-in-textview-27bb70b2d31c (https://github.com/saket/Better-Link-Movement-Method) is a solution.

**Comment by binwiederhier** [comment]
Fixed in https://github.com/binwiederhier/ntfy-android/commit/4771ccc6c0e98892299b50f3eeef3a92acfba8c0

I also tried the link movement method above, which highlights links nicely when they are clicked and allows for long-click options. However, the long click does not work properly because the long-click-select-row logic interferes with it. So for now I won't add this. It'd be nice though to open a menu to "copy" or "open" the link on long click
