### ISSUE TITLE
YAML variables shouldn't use dashes

### ISSUE THREAD

**Issue by ajdelgado** [binwiederhier/ntfy#255]
Hi,
The YAML specification defines a dash as a special character and can't be used for variables. This makes the configuration file for ntfy not complaint causing first an issue to check correct syntax but in my case an issue creating an Ansible Role. what could be a simple YAML2YAML process needs translation to set the dashes.
I guess the easier solution for the community would be allowing defining with dashes or underscores for a while, and deprecating the dashes at some point.
Maybe this should be a new feature request, but it actually breaks tests.

**Comment by binwiederhier** [comment]
Thank you for using ntfy and for reporting this. Well that's a bummer with the config options. I'm using the urfave/cli library and it does all the config loading for me. It's using the config options as CLI options and config file options, which is why _ are kind of ugly. Maybe I could just make it support both. Aliases are already supported by the library. Could be a super simple ticket.

In the meantime, you could probably use environment variables in Ansible, no?

**Comment by binwiederhier** [comment]
Reference: https://github.com/binwiederhier/ntfy/blob/main/cmd/serve_linux.go#L22

**Comment by binwiederhier** [comment]
This is done in https://github.com/binwiederhier/ntfy/commit/91594faf288d13bd128067436e11345dc7a9d583 and will be in the next release. Thank you for reporting @ajdelgado.
