### ISSUE TITLE
docs: clarify what happens when it fails to connect to upstream base url 

### ISSUE THREAD

**Issue by prabirshrestha** [binwiederhier/ntfy#299]
What happens if upstream-base-url is set but fails to send to the upstream server. This could be due to temporary internet connection issue or upstream server in maintenance mode. Will this be retried or will be lost?

**Comment by binwiederhier** [comment]
Thanks for this question!

The docs [already say this](https://ntfy.sh/docs/config/#ios-instant-notifications):

> If `upstream-base-url` is not set, notifications will still eventually get to your device, but delivery can take hours,
depending on the state of the phone. If you are using your phone, it shouldn't take more than 20-30 minutes though.

This is facilitated by the `~poll` topic, which all iOS devices subscribe to. The server sends a keepalive message to the iOS app every 20 minutes, which triggers it to poll all subscriptions. This is the only way on iOS to run scheduled code. Otherwise I would have used a timer for that. 

I think the docs are sufficient for this. The implementation details are not that important and may change. I'm closing this for now.
