### ISSUE TITLE
iOS - no notification on Apple Watch

### ISSUE THREAD

**Issue by Famku** [binwiederhier/ntfy#317]
Hi,

I dont know if this a bug or a feature request, but I dont receive any notification on my Apple Watch.

Notifications on my iPhone works well.

**Comment by binwiederhier** [comment]
I sadly do not have an Apple Watch, and I don't think I'll acquire one any time soon. So that'll make it quite difficult for me to test this. I think I need to create a watch extension (https://github.com/firebase/firebase-ios-sdk/tree/master/Example/watchOSSample/SampleWatchAppWatchKitExtension), but unless someone volunteers, I don't see myself doing this, sadly.

**Comment by Famku** [comment]
If you want to implement this in a test version, I can test it.

Ansonsten ist ja bald schon wieder Weihnachten ...^^

**Comment by ozskywalker** [comment]
emojis working here. Anything special about the emojis you're using?

![image](https://user-images.githubusercontent.com/5518808/202924441-60d148c0-f2f8-4153-a7a3-754a29e5fc8d.jpeg)

watchOS 8.7.1
iOS 16.1.1
ntfy.sh public server

**Comment by Famku** [comment]
@ozskywalker 

you are right, it works also for me now.

Thanks for testing
