### ISSUE TITLE
Let user choose delivery mode: instant delivery, 1min, 5min, 15min, ...

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#32]
Make delivery mode configurable in the app:

* instant (requires foreground service)
* 1min (requires foreground service)
* 5min (requires foreground service)
* 15min (does NOT require foreground service)
* ..

**Comment by m0Re-p** [comment]
Im waiting on this feature :)

**Comment by binwiederhier** [comment]
@m0Re-p Just curious, are you waiting for this because you don't like the foreground service? Or are you having battery concerns? If so, is non-instant delivery not enough, or are you on the F-Droid flavor?

**Comment by m0Re-p** [comment]
@binwiederhier I prefer F-droid options

Im using tasker with some plugins to monitoring temperature on my central heating stove. Tasker make a photo on every 2 minutes, use ocr to read temperature, save the results in CSV file. If temperature are greater then XX value I receive notifications. Using ntfy I can control my phone by any other devices

**Comment by binwiederhier** [comment]
That's wild. Very cool. 😎

So you'd only want to check every two minutes instead of instant? Why? Battery? I'd assume your phone to monitor the stove is plugged in, right?

**Comment by m0Re-p** [comment]
@binwiederhier thank you :)

Yes, example check every two minutes (but the better solution is situation when I can put any value what I want).

You are right, my phone to monitor the stove is plugged in but In m my head I have a lot more ideas to use ntfy where this functionality is really necessary 

Anyway this tool are really good. I launched my instance on RPI and works good too

**Comment by binwiederhier** [comment]
I am inclined to close this, since the main reason for it was saving battery. Since that's no longer an issue, and the foreground service can be easily hidden, I'm going to close this.

Please re-open if this is desperately desired.

**Comment by Fabian-G** [comment]
For what it's worth: I'd love to see this feature. Although the battery usage of ntfy is somewhat okay-ish, it is (at least on my device) not insignificant. On the other hand I usually don't really care if a notification arrives immediately or at some point within an hour, because my phone is in silent mode 24/7 anyway.
Currently ntfy sits at 4-5% per 3 hours in my battery stats. With a WorkManager based approach (or whatever you had in mind) I would expect ntfy to hardly show up in the stats at all. Therefore, I think it would be great if the user had control over this.

**Comment by McOrvas** [comment]
I use Ntfy with a self hosted server at home. My Android phone (Pixel 6, Android 16) is connected with WireGuard to my home network when I'm on the go. In my home Wifi a have absolutely no problems with the battery usage and even in other Wifis together with an active WireGuard connection it is not a problem. But with mobile data and WireGuard Ntfy really drains the battery in a short time. For my personal purposes it would be perfect to have the possibility to select a poll interval instead of the persistent connection.
