### ISSUE TITLE
setting.yaml base-url comment might want to refer to iOS notifications

### ISSUE THREAD

**Issue by milksteakjellybeans** [binwiederhier/ntfy#322]
When using the "upstream-base-url" option without using the "base-url" option ntfy serve will output:

```
if upstream-base-url is set, base-url must also be set
```

From settings.yaml:
```
# Public facing base URL of the service (e.g. https://ntfy.sh or https://ntfy.example.com)
# This setting is currently only used by the attachments and e-mail sending feature (outgoing mail only).
#
# base-url:
```
This^ section may need updating to refer to base-url use as part of the iOS notifications feature, in addition to the mention of attachments and email.

thank you

**Comment by binwiederhier** [comment]
Fixed in https://github.com/binwiederhier/ntfy/commit/41096ef1b06eff9624612fae28a1fc740b5af6dd

If you can, why don't you try to create a pull request for things like this (docs updates, simple changes) next time. That'd help me a lot :-) If not, don't worry about it. 

Thank you for reporting this (and the other tickets!!)

**Comment by milksteakjellybeans** [comment]
sure, I will try to figure it out, I am new to GitHub

**Comment by binwiederhier** [comment]
This will probably help: https://www.youtube.com/watch?v=rgbCcBNZcdQ
