### ISSUE TITLE
Orderable user action buttons

### ISSUE THREAD

**Issue by dcousens** [binwiederhier/ntfy#380]
The typical preference of action buttons on Android notifications at the moment is, with an `attachment.url`, the following:

- Open
- Browse
- `{User Actions}`
- ...

Where `Open` and `Browse` are provided by the `ntfy-android` application using internal semantics.
The semantics are defined at https://github.com/binwiederhier/ntfy-android/blob/60f90667d9d252487de21d481507647fb368349d/app/src/main/java/io/heckel/ntfy/msg/NotificationService.kt#L76-L83 , and for the example above, assumes the download worker didn't fail or wasn't in progress.

Unfortunately, if you have `N>1` user actions, you may end up with **only the first user action being usable** (unless you open the application),  with the others being dropped by your device's notification action bar.  For me at least, 3 is the limit for my device.

# Proposal
I propose that user actions should be have an order priority that we can use to place them before or after the `Open` and `Browse` actions.  If we used the following values:

| Action | Default Order Index |
| -------- | -------- |
| Open | 1 |
| Browse | 2 |
| Download | 3 |
| Cancel | 4 |

We could provide an `action.order = 0` to put user actions before `Open`, or `action.order = 1` to place them before `Browse`.
We could provide an `action.order = 5` to put them at the end of the list.  `5` (or `99`) could be the default, so as to not change the current behaviour.

# Alternative proposal
If this is unwanted complexity,  we could instead change the order of user actions being added to the following:

- `{User Actions}`
- Open
- Browse
- ...

---

If you are interested in this @binwiederhier but only open to a pull request (not implementing it yourself), I am happy to try and take this on.

**Comment by binwiederhier** [comment]
This obviously only applies to notifications with an attachment AND >1 user actions, because the Android limit for buttons is 3 (as you mentioned above). 

I am conflicted: That seems to be a real edge case, since you could just push another message; but I do get that it takes away from the infinite flexibility of designing your notifications the way you want. 

Paging @wunter8 for thoughts/input.

**Comment by wunter8** [comment]
Doing the second option, of just having the user actions first, would be pretty easy to implement. Easy enough that I'd say, "Sure, why not?" But do we make it the new default or just a configurable option?

Having custom button ordering per notification would be a much more significant code change, so I'd be less tempted to do that, at least right now

**Comment by binwiederhier** [comment]
>  just having the user actions first
Arguably user defined actions are more important. It feels a little weird, but I think I'd be okay with that.

> But do we make it the new default or just a configurable option?

No. It's not important enough for that.

> Having custom button ordering per notification would be a much more significant code change, so I'd be less tempted to do that, at least right now

Agreed.

**Comment by wunter8** [comment]
> No. It's not important enough for that.

I presume you mean it's not important enough for a configurable option, so I'll just plan on making it the new default. I just hope it doesn't negatively affect anyone that's used to the way it is right now

**Comment by binwiederhier** [comment]
> I just hope it doesn't negatively affect anyone that's used to the way it is right now

We shall see :-)

**Comment by binwiederhier** [comment]
I'm going through tickets right now, and honestly I don't think this is of any/high value to most users. I've never heard anyone complain about the way that action buttons work or are ordered. 

So I'm closing this for now. Feel free to comment and we can discuss further.

**Comment by dcousens** [comment]
Unfortunate, but I understand that I appear to be the only signal :signal_strength: for the feature.

**Comment by computer-geek64** [comment]
I noticed this issue on Android as well, and I would definitely like to see a fix for this if possible. While I agree this seems like an edge case, I don't think having multiple actions and an image in a notification is too unrealistic.
I'd also like to add that instead of developing a mechanism for ordering, a simpler idea might be to simply add additional arguments for the "attach" parameter to enable or disable the default actions of open and browse.

**Comment by mjmccans** [comment]
I too would appreciate this feature, and the suggestion offered by @computer-geek64 above would work for my use case. Another solution would be to have an option when you are setting a user action, perhaps named something like "prefix" or "before", that defaults to "false" but if set to "true" would put the user defined actions before the default actions. That being said, I personally think @computer-geek64's suggestion is better because you will end up with cleaner notifications if you have only one or two user defined actions. 

In case it is helpful, I can briefly describe my use case because I don't think it is that odd or unique. I want to receive a notification when my doorbell camera detects a person. The notification has a thumbnail of the activity attached, and I want to also have three actions: (1) view the associated snapshot image, (2) view the associated video clip, and (3) view the live stream from the camera. For my use case the "Open" and "Browse" actions are not useful, and stop me from being able to have the other actions that I need. An ability to turn off the default actions would be fantastic.

Either way, ntfy is fantastic and that you very much for all of the hard work you have put into it.
