### ISSUE TITLE
Allow to put web-ui on separate port/host

### ISSUE THREAD

**Issue by pinpox** [binwiederhier/ntfy#459]
I'd like to put the web-ui on a different port or a different subdomain, but couldn't find an option to do so.
This might also be workarount for #238, as it allows to set a password in the reverse proxy you might run in front of ntfy

**Comment by binwiederhier** [comment]
Could you elaborate on the use case? Why it be useful to split the web app and the API?

**Comment by pinpox** [comment]
> Could you elaborate on the use case? Why it be useful to split the web app and the API?

E.g. to make the webUI only accessible via an internal URL or VPN. I know that the client itself does not provide acess to any confidential information without having the credentials, but I don't want it to be visible/accessible for anyone.

**Comment by binwiederhier** [comment]
It feels a bit arbitrary and doesn't really need to happen in ntfy (you could do this in nginx or apache), so I think I'm going to take the liberty to say "no" to this request. ntfy already has a lot of config options and is more confusing than I'd want it to be. This seems unnecessary, since it is a cosmetic change with no real security/other benefit.

In nginx, you can restrict routes for certain IP ranges easily, so you don't need ntfy to help you via a different port.

Keep the tickets coming, and don't be discouraged by me not implementing everything.

**Comment by pinpox** [comment]
Makes sense, in that case I'd suggest adding an example of how to set this up in the docs, since there is already an example on the [reverse proxy setup](https://ntfy.sh/docs/config/#behind-a-proxy-tls-etc). I tried earlier with nginx but couldn't get it to work properly. If I'm successful I'll let you know
