### ISSUE TITLE
Clarification on example in iOS instant notifications

### ISSUE THREAD

**Issue by jpmens** [binwiederhier/ntfy#465]
The example of what is transferred to `ntfy.sh` in https://github.com/binwiederhier/ntfy/issues/300 is slightly confusing, and I hope you can clarify this for me.

The example shows what the self-hosted server forwards to the upstream server:

```console
curl -X POST -H "X-Poll-ID: s4PdJozxM8na" https://ntfy.sh/6de73be8dfb7d69e32fb2c00c23fe7adbd8b5504406e3068c273aa24cef4055b
{"id":"4HsClFEuCIcs","time":1654087955,"event":"poll_request","topic":"6de73be8dfb7d69e32fb2c00c23fe7adbd8b5504406e3068c273aa24cef4055b","message":"New message","poll_id":"s4PdJozxM8na"}
```

Is the attribute `message` really contained in what is sent upstream? IMO that would defeat the actual purpose of hiding the published data.

**Comment by binwiederhier** [comment]
It literally sends the message "New message" for every message. Even if your message is "Some other message", the message will always be "New message". This is so that if iOS cannot talk to the selfhosted server (in time, or at all), it'll show "New message" as a popup. 

https://github.com/binwiederhier/ntfy/blob/cbc912d1e35f365116a96109cf0fc7ae28cd575d/server/server.go#L96
https://github.com/binwiederhier/ntfy/blob/cbc912d1e35f365116a96109cf0fc7ae28cd575d/server/types.go#L116
https://github.com/binwiederhier/ntfy/blob/cbc912d1e35f365116a96109cf0fc7ae28cd575d/server/server.go#L463
