### ISSUE TITLE
Android app not sending username/password for attachments

### ISSUE THREAD

**Issue by jakobdalsgaard** [binwiederhier/ntfy#487]
When sending a message with an attachment, picture for example, and this attachment is served from the ntfy server itself, then the request from the app to fetch the image is not sent with the credentials specified in the app for said host.

I run my own ntfy server behind nginx, with TLS and basic authentication; but I need to disable auth for the '/file/' path in the nginx for the android app to be able to fetch the attached image -- I would prefer preventing serving this content to the world by requiring the same password for these files as for any other access to the ntfy server.

I've tried to see if anyone else has seen this behaviour, but I could not find any issues submitted to github.

My ntfy server install is the amd64 debian package version 1.28.0 and the Android app reports 1.14.0 (play)

**Comment by binwiederhier** [comment]
The filename of the attachment is the message ID, which is 12 random characters (a-zA-Z0-9), which is (26+26+10)^12 = 62^12 possible file IDs. So unless you know the message ID (which you don't, because that implies that you know the message), you cannot guess the attachment URL. And that's why the username and password is not required for attachments. 

I hope that explains it.

**Comment by jakobdalsgaard** [comment]
Unless you intercept a message, say an email -- then you don't have to guess - and you don't need username/password to get the image. A few comments:

1) this is security through obscurity
2) it's counterintuitive that I can configure the Android app to use username/password for an ntfy server, and then it does not apply said username/password on certain requests to said server.

I do understand, from your explanation, that is works as designed, and I'm thus questioning the design :-)

**Comment by Ali2731** [comment]
thanks

**Comment by binwiederhier** [comment]
Thank you for your feedback. I appreciate you taking the time to investigate and comment.

However, I do not agree with your assessment. A secret URL with a long randomly generated identifier is not security through obscurity. In fact, it is common practice in the industry: Google Photos, GitHub, Discord, Slack, ... Everyone uses this method to serve user content such as images and other media. Here's an example from a private channel in a private Slack instance: https://files.slack.com/files-pri/T01QXA3BC8Y-F04AR1DKU81/2q__.jpg

Security through obscurity implies that you can access a resource or component without knowing a secret, because you've discovered a way around it. The file ID is a secret (as mentioned above), and you cannot access the file without it.

**Comment by binwiederhier** [comment]
Closing this for now. But I'm happy to keep discussing.

**Comment by jakobdalsgaard** [comment]
:-) you have some fair points; and this is definitely something that you have thought of - I'm good with that; though I do not fully agree with you. We don't have to.
