### ISSUE TITLE
Confusing UnifiedPush topics in Android app

### ISSUE THREAD

**Issue by kwoot** [binwiederhier/ntfy#500]
Hi,
I start playing around with ntfy on Linux and Android. Great stuff!

First line shown in the screenshot my own testing using the public server, and later renaming it to a non-existent server in my own domain.
The other lines in Ntfy on Android seems to show spam messages. The seem to come from a "unified push".

Is this only me? Or a known problem? Or am I doing something wrong?

Love to know.

Warm regards and thanks for an awesome project and tool!
![Screenshot_20221109-213849](https://user-images.githubusercontent.com/484336/201894718-32a6fb57-986a-4848-bb7f-bcc678b75875.png)

**Comment by binwiederhier** [comment]
Tusky is using ntfy as a UnifiedPush distributor (https://unifiedpush.org/). It's not spam. It registered topics to deliver messages from its server to the Android app, instead of using Google's FCM. I'm sure you can change this in the Tusky settings. 

Two things:

1. ntfy topics are secrets, so I suggest you remove the screenshot and/or change the topics you are using
2. Your personal ntfy server seems to be having connection issues. I just checked with curl and I don't think the domain is a ntfy server. It redirects to www.yourdomain.com
