### ISSUE TITLE
Use DNS SRV records for the default server setting

### ISSUE THREAD

**Issue by piwi82** [binwiederhier/ntfy#603]
The _Default server_ setting in the mobile application (Android/iOS) could be eased by using only the domain name (`domain.tld`) instead of the full URL (https://ntfy.domain.tld) through a DNS SRV record.

Syntax : `_ntfy._tcp.domain.tld. ttl IN SRV priority weight port target.`
Example : `_ntfy._tcp.ntfy.sh. 600 IN SRV 0 0 443 ntfy.sh.`

Mine would look like : `_ntfy._tcp.domain.tld. 86400 IN SRV 0 0 443 ntfy.host.domain.tld.`

This way, the user has just to input `domain.tld` in _Settings_ > _GENERAL_ > _Default server_ (also in _Settings_ > _USERS_ > _+ Add user_ > _Service URL_) and let the applications resolve `_ntfy._tcp.domain.tld` (and build the URL).

You will probably have to check the **port** value to determine whether `http` or `https` should be used :
- No ambiguity if a standard value is used (80 or 443),
- If another value is used, try `https` first. Fallback to `http` if `https` failed (https://ntfy.sh:8088 > http://ntfy.sh:8088)

No hard work, just happy end users 😀 (#597 is a good one too)

**Comment by binwiederhier** [comment]
While this is a fascinating idea, I do not see a lot of value in it, especially since the base-url concept is pretty much ingrained into every fiber of ntfy. If anything, this is a UX problem: We could ease the URL entry, or have the Android/iOS/web app probe the URLs automatically.

Most users do not know what a SRV record even is. Many do not have their own DNS server, or control all aspects of it.

I am taking the liberty of closing this as WONT DO. I hope you understand. Please keep other ideas coming. I love seeing ideas like this.

**Comment by piwi82** [comment]
I do understand 😉 
This one certainly has the lowest priority regarding other requests like links #587 and markdown #1072 on mobile.
