### ISSUE TITLE
unifiedpush: Some servers send invalid "Authorization" header, which leads to 401 responses

### ISSUE THREAD

**Issue by Boebbele** [binwiederhier/ntfy#629]
Unifiedpush dont works on iodeos with microg.
Ntfy Github fdroid Version. 
Push messages with curl from terminal works great.

But unifiedpush dont works. Tested with fedilab, tusky and fluffychat. 

If I use unifiedpush with conversations an its integrated pushserver it works perfekt.

**Comment by bama35453** [comment]
Additional information:
ntfy also stopped working on Samsung devices after the latest firmware update (Android 13).
Tested with Tusky and Fedilab on a Samsung Galaxy Tab S7  and a Samsung Galaxy S22 Ultra.

**Comment by binwiederhier** [comment]
This is not enough information. 

Both ntfy on Android and the ntfy server have significant logging capabilities. Please post some logs or investigate further:

- ntfy Android: Settings -> Record logs
- ntfy server: Turn "log-level: DEBUG or TRACE"

**Comment by bama35453** [comment]
Well the log file doesn't show anything except for the NtfySubscriberConn entries telling "Connection is active" which show up every 30 seconds.
I received some notifications in the meanwhile, but none of the show up in the log in any way.

**Comment by Boebbele** [comment]
survey on problems with UnifiedPush on Mastodon: https://blueplanet.social/@nichu42/109908840871096554
Perhaps it helps...

**Comment by binwiederhier** [comment]
@S1m approached me and explained the actual problem. It seems that some app servers send an `Authorization` header to ntfy, even though they do not need or should. As of 2.0, ntfy treats the existence of that header as an attempt to authenticate.

In order to support these faulty servers, I'll make a change to treat any headers that are not `Basic` or `Bearer` as if they did not exist.
