### ISSUE TITLE
Allow finer control over UnifiedPush in the android app

### ISSUE THREAD

**Issue by ollien** [binwiederhier/ntfy#646]
Right now, if an app wants to use UnifiedPush, it can simply register itself. This causes ntfy to use instant delivery, which makes sense given the usecase of UnifiedPush, but is a bit frustrating if you only wanted to use ntfy for other pushes and don't want the battery drain of instant delivery. 

Ideas for possible controls:
1. An option to disable UnifiedPush entirely
2. An option to block a specific app from enabling UnifiedPush
3. An option to disable instant delivery for a UnifiedPush topic

I don't know how the project feels about any of these, but I imagine that #1 is perhaps the "easiest" (said without much context).

**Comment by binwiederhier** [comment]
(I am assuming that you are talking about the Android app)

I used to have a toggle in the Settings that allowed disabling UnifiedPush entirely, but I removed that because I didn't want toggle-hell. I haven't heard this argument before, to be honest. Usually you can choose the notification method in the app itself and unselect "ntfy" there. What app is misbehaving and registering itself without your consent?

**Comment by ollien** [comment]
Yeah, I am.

The offending app is Tusky. As far as I can tell there's no option for it. See this issue https://github.com/tuskyapp/Tusky/issues/2692

**Comment by binwiederhier** [comment]
I'd be ok with an off switch for UP if somebody wants to implement it (_cough_, @wunter8, maybe?)

**Comment by binwiederhier** [comment]
@wunter8 Did this already.
