### ISSUE TITLE
much more battery hungry than other apps with open connections

### ISSUE THREAD

**Issue by kolAflash** [binwiederhier/ntfy#718]
ntfy seems to use much more battery than other apps which keep open network connections.

Phone: Fairphone 3+
OS: eOS-1.4 (Android-10)

<details>
<summary>see screenshot</summary>

![Screenshot_20230506-102220_Einstellungen](https://user-images.githubusercontent.com/3355089/236612657-79187a70-ab96-48db-9cb6-1c14da4785a6.png)
</details>

For example Conversations. It has two XMPP accounts logged in. And I'm opening Conversations in foreground quite often. Nevertheless, Conversations needs less battery than ntfy. Same when comparing to microg.

Please check if you can optimize battery usage!

&nbsp;

Although this might be counter intuive:  
What about adding a mode to receive a notification via PlayServices (microg) to wake ntfy? Instead of keeping an open connection. This still has better privacy than pure PlayServices, because PlayServices won't know which notifications ntfy will then receive from it's own server.

**Comment by binwiederhier** [comment]
The battery usage is already pretty optimized and uses <1% per day for pretty much everyone out there. This must be a problem with your phone or configuration. In my limited personal experience, the Fairphone is not the greatest phone in various aspects, so maybe it's that. Feel free to drop in the Discord/Matrix to discuss, but I won't do any more battery work, because it's been solid for over a year.
