### ISSUE TITLE
Missing translation in web app

### ISSUE THREAD

**Issue by codebude** [binwiederhier/ntfy#730]
:lady_beetle: **Describe the bug**
In the web app, there's a part  (Account -> Attachment storage -> subheading) which doesn't seem connected to the localization engine. I use the German UI, but the text is still English. Weblate says, that all texts (100%) are translated for German. Thus I assume, that the part isn't linked correctly with the "translation engine".

It is this text: https://hosted.weblate.org/translate/ntfy/web/de/?q=expiry&sort_by=-priority%2Cposition&checksum=

:computer: **Components impacted**
- web app

:bulb: **Screenshots and/or logs**
![image](https://github.com/binwiederhier/ntfy/assets/2236234/ba695284-bf41-4aae-b68a-e223b8d07a60)

:crystal_ball: **Additional context**

- It seems that only the `{expiry}` part isn't translated correctly.
- This bug occurs only, if a user hasn't set a specifc language in his/her account settings (=language selector box in settings is empty). As soon, as one sets the language explicitly (Settings -> Appearrance -> Language) to German, even the `{expiry}` part is translated correctly.

**Comment by binwiederhier** [comment]
I looked at this briefly, thinking it was going to be an easy fix, but it turns out that I think I may have messed up some of the i18n stuff, or at least I'm not understanding it well enough. I believe your locale is set as `de-DE` or `de-AT` or similar, and my language files are only called `de.json`. The same problem exists with English and `en-US`, etc. 

Long story short, it's not loading the correct language because `i18n.language` is set to `de-DE` instead of `de`. The language detection stuff apparently does fall back from `de-DE` to `de`, but I don't know how to get to that variable (yet).

**Comment by binwiederhier** [comment]
Oh maaaan, I should have read your comment first. Because you solved it the same way I eventually did, except that I did my own research when I didn't have to. Good thing we came to the same conclusion. 

Fixed in https://github.com/binwiederhier/ntfy/commit/f998d4d2adc4f582035eb37cf0537eb2d0b1e272

Thanks for reporting, and for the solution!

**Comment by codebude** [comment]
You're welcome...
...und viele Grüße aus der Heimat. ;-)
