### ISSUE TITLE
PWA Docker

### ISSUE THREAD

**Issue by mmojadad** [binwiederhier/ntfy#800]
Hello
I am usinf ntfy in docker via persistent cache mode.
What will be steps to enable progressive web app (PWA), What exact command i must to use to generate VAPID keys?

**Comment by nimbleghost** [comment]
Hi @mmojadad, please follow the instructions here: <https://docs.ntfy.sh/config/#web-push>

You can generate the keys like this:

```sh
docker run --rm -it binwiederhier/ntfy webpush keys
```

Then copy them to your config file. Don't forget to also add a `base-url` along with the generate values if you don't have one already.

**Comment by gedw99** [comment]
@nimbleghost 

thanks I was also stuck on the vapid thing 

https://docs.ntfy.sh/config/#web-push Does not mention this from my quick reading. Correct me if I am wrong 

Also a web gui for configuring things should be pretty easy to add using go templates. If that something you would support ? Can make an issue

**Comment by nimbleghost** [comment]
@gedw99 what do you mean :D

![Screenshot of docs.ntfy.sh/config/#web-push, highlighting the section with `ntfy webpush keys`](https://github.com/binwiederhier/ntfy/assets/132819643/33c06ca0-2442-4df2-aaf1-7945d735a61e)

--

I think the trouble with config web UIs is that you either make the config part of the database, or need to have a way to restart the server itself to reload the new files + have to make sure configs are writeable etc. I think it's not really worth the effort for minimal gain, especially since people hosting ntfy are running their own servers and shouldn't have trouble figuring out some YAML/commands

**Comment by mmojadad** [comment]
@nimbleghost Thank you!
I did it but still PWA not showing, My installation environment is as following:
--------------------
persistent cache (configured as command line arguments):

docker run \
  -v /var/cache/ntfy:/var/cache/ntfy \
  -p 80:80 \
  -it \
  binwiederhier/ntfy \
    serve \
    --cache-file /var/cache/ntfy/cache.db
---------------------
I am using Portainer and after generate keys i edit and add environment variables followings to the container :

web-push-public-key :  ///
web-push-private-key : ///
web-push-file : /var/cache/ntfy/webpush.db
web-push-email-address : myemail@gmail.com
base-url : https://mydomain.com

**Comment by nimbleghost** [comment]
You're probably mixing up the key for the config file and the env vars. If you want to set them up as environment variables you need to use the equivalents[^1], for example `NTFY_WEB_PUSH_PUBLIC_KEY`. Look at the list for the rest.

[^1]: https://docs.ntfy.sh/config/#config-options

**Comment by mmojadad** [comment]
@binwiederhier Thank you for corrections, Yes i fixed the keys and now its working fine :)
