### ISSUE TITLE
Repository organization

### ISSUE THREAD

**Issue by johnlpe** [binwiederhier/ntfy#806]
This repository is quite big. Could we make GitHub organization and set under it own repositories for the server, Android client, iOS client, docs and so on.

**Comment by binwiederhier** [comment]
I couldn't get https://github.com/ntfy, otherwise I would have moved the other stuff in an org already. I got @ntfy-sh and @ntfysh, but I hate both, because "ntfy.sh" is the SaaS business, not the open source project. I do, however, like that the docs and web app are all in one place. I don't intend to change that.

Keep the ideas coming. I love it.

**Comment by johnlpe** [comment]
> I couldn't get https://github.com/ntfy, otherwise I would have moved the other stuff in an org already.

ntfy-project? Very common to add -project to the end.

> I do, however, like that the docs and web app are all in one place. I don't intend to change that.

Docs is fine, but could you separate own repos for the clients and the server.

**Comment by johnlpe** [comment]
ntfy-org, ntfyorg or NtfyOrg if you buy ntfy.org domain :laughing:
