### ISSUE TITLE
Can't connect to server from IOS

### ISSUE THREAD

**Issue by lilcutiesquirt** [binwiederhier/ntfy#908]
:lady_beetle: **Describe the bug**

I have a server running from linode that i've linked, however when trying to connect with the https:// format it doesn't connect to the server. I know the server is running as i've opened and run it from the terminal 

:computer: **Components impacted**

kali linux, linode, windows

:bulb: **Screenshots and/or logs**

:crystal_ball: **Additional context**

**Comment by Trystan34** [comment]
For iOS you need to configure "https://ntfy.sh/" as "upsteam-base-url" in your server.yml.
See: [iOS instant notifications](https://docs.ntfy.sh/config/?h=#ios-instant-notifications) for futher details.

Also on your server.yml config ensure that you set your base-url to your Linode address
base-url: 192.168.1.10 -> base-url: https://linodeexample.com

**Comment by davesnthere** [comment]
Having the same problem here. I've tried my upstream ad my dns name and ip address. I'm running a different port 4554 and forwarded through my firewall. Tried 4554>4554 and 4554>80.
Do we need SSH for this to work?

**Comment by Trystan34** [comment]
@davesnthere I am running the NTFY server on Docker. My server listens on port 8080 (http) not SSL but due to the one of the useful features of CloudFlare, it provides a toggle for auto SSL encryption to the domain even though the actual NTFY server is listening on HTTP.

Originally I had my base-url set to the static ip of my Rasberry Pi but I did not receive the notifications, since changing it to my domain with https (even though I do not have HTTPS enabled in the ntfy server.yml) it works now.

I don't think you need SSH for it work however, your hosting is different to mine?

![image](https://github.com/binwiederhier/ntfy/assets/2108308/a3973b46-c06b-4384-88ef-c420c3a3db98)

My docker-compose file
```yaml
version: "2.3"

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=NZDT # optional: set desired timezone
    #user: 1000:1000 # optional: replace with your own user/group or uid/gid
    volumes:
      - /var/cache/ntfy/cache.db:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    ports:
      - "8080:80"
    restart: always```

**Comment by davesnthere** [comment]
@Trystan34 Gave that a try with no luck.
Been trying all sorts of configurations. The only thing I can think of is, I'm running this from a Proxmox unprivileged container. 
If anyone is on Proxmox and running ntfy, is this working for you?

**Comment by SuperdukeGates** [comment]
Hi @davesnthere , are you able to check the logs ?

For my case, I use Nginx reverse proxy to pass traffic to the local Ntfy server. I have HTTPS for Nginx while Ntfy server is plain text HTTP.

In the `/etc/ntfy/server.yml`, I configured the `base-url` to access my Nginx and internet accessible. Also configured this `upstream-base-url: "https://ntfy.sh"` for iOS.

If all the setups above are correct, the ntfy-ios app would access the URL as configured in `base-url` and you can see the request in the Nginx's access log or error log in case certain errors happened.

If the logs are nothing about the request from the ntfy-ios app, then the problem maybe the network problem such as firewall, DNS resolving etc.

**Comment by binwiederhier** [comment]
Configuration problems like this are typically best solved in chat on Discord/Matrix. I do not think there there is a bug here, merely configuration issues.
