### ISSUE TITLE
SSL Certificate error

### ISSUE THREAD

**Issue by hunnomad** [binwiederhier/ntfy#910]
The certificate used by Certbot is set on the Nginx server, and the ntfy server is behind Cloudflare.

![Screenshot_20231007_121638_ntfy](https://github.com/binwiederhier/ntfy/assets/2537005/1bb847ef-ba67-4fca-9d52-6e4b4716407e)

**Comment by babiloof** [comment]
I had the same issue and in my case i had generated a cert.crt file for Nginx reverse proxy with the command

openssl pkcs12 -in cert.pfx -clcerts -nokeys -out cert.crt

witch does not include intermediate certificates so i removed "-clcerts" from the command and generated a new cert.crt file with the intermediate certificates included. Restarted the Nginx reverse proxy with the new cert.crt file and the error was gone.

So i belive the issue was that intermediate certificates was missing.

**Comment by binwiederhier** [comment]
> So i belive the issue was that intermediate certificates was missing.

Just from the error message "trust anchor is missing", this seems to be the case.

`certbot` provides a `cert.pem` and a `fullchain.pem`. Be sure to pick `fullchain.pem`. 

Closing this issue as it is not related to ntfy at all.
