### ISSUE TITLE
[HOW] how do i get notifications when a message received when the app is terminated (flutter android)

### ISSUE THREAD

**Issue by iamrishan** [binwiederhier/ntfy#924]
I'm using the ntfy API to receive notifications on my own app in Flutter/Android.
I completed the part to receive notifications when the app is in the foreground or background using a package called flutter_local_notifications.
but when the app is closed/terminated no notification is coming. how do I implement  this with ntfy API

**Comment by wunter8** [comment]
When you close the app, it's closing the connection to the ntfy server.  You'll probably want to look into and implement UnifiedPush. Or you'll need to implement something else to keep a connection to the server open in the background

**Comment by iamrishan** [comment]
Yeah! I know Firebase has a background function to workwith background notification using FCM.

**Comment by wunter8** [comment]
The ntfy Android app typically keeps a persistent connection open to the ntfy server using a background process/service. If that persistent connection fails (and the app was installed from the Play Store and not from F-Droid), ntfy will fallback to receiving notifications via FCM, which does work in the background, like you said.

All of the Android code is open-source, so you can look at it directly to see how things work. https://github.com/binwiederhier/ntfy-android It is in Kotlin, though, not Flutter/Dart.

UnifiedPush is cool because it lets your app receive notifications through ntfy's persistent connection. So you don't need to worry about setting up any sort of persistent network connection with graceful FCM back up. As long as ntfy is installed on the same device as your app, your app can benefit from ntfy's persistent connection. In your app, I believe all you need to do is set up a BroadcastReceiver that listens for UnifiedPush messages.

This describes UnifiedPush more and includes a Flutter example: https://unifiedpush.org/developers/flutter/

**Comment by iamrishan** [comment]
Thanks for the insight. I will check on the resources

**Comment by iamrishan** [comment]
@wunter8  hey I tried to implement it with FCM. I stuck where I need to subscribe to a topic in FCM to receive notifications in the background .
I tried the same topic as my nfty topic but I think that's not it.
do you tend to know what will be the server topic for my specific nfty topic (eg. mytopic in ntfy.sh)?


![image](https://github.com/binwiederhier/ntfy/assets/52799367/6fdb8e43-4148-4744-ad38-bb2c0868c6b7)

**Comment by wunter8** [comment]
I don't know for sure. I haven't used FCM very much. But I'm pretty sure you can use whatever you want. Since you're building the app, you get to decide how notifications and subscriptions work. I believe ntfy is set up to subscribe to a FCM topic that's the same as the ntfy topic, though

**Comment by iamrishan** [comment]
thanks
