### ISSUE TITLE
Instant Delivery not working

### ISSUE THREAD

**Issue by 12nick12** [binwiederhier/ntfy#97]
Hi, I have a Pixel 4a 5G and the instant delivery doesn't work. The persistent notification is there showing it's running, but still requires me to pull down to reload to get the new notification.

**Comment by binwiederhier** [comment]
@12nick12 If you're willing to join the Discord or Matrix chat, I can troubleshoot with you.

https://discord.com/invite/cT7ECsZj9w
https://matrix.to/#/#ntfy:matrix.org

I don't have a good way to get logs yet, I'm working on making that easy.

**Comment by 12nick12** [comment]
All good, I'm dumb. I used a NGiNX config from another thing that didn't have websockets. Sorry about that.

**Comment by binwiederhier** [comment]
@12nick12 I'm glad you fixed it. It doesn't use websockets (yet) though. :-D Must have been something else then.

**Comment by ericsong** [comment]
I was also having issues with instant delivery and it turned out to be an issue with my NGINX config. I had to turn off [proxy buffering](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering).

**Comment by binwiederhier** [comment]
@ericsong The example in https://ntfy.sh/docs/config/#nginxapache2caddy includes `proxy_buffering off`. You should probably make sure that you've also got the other settings in there. Especially make sure that stuff works with WebSockets too, otherwise the next or the following release of the Android app may not work anymore for you.

```
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
```

You can test your settings in the app by enabling WebSockets: Settings -> Experimental -> Connection protocol -> WebSocket

**Comment by ericsong** [comment]
Ah, missed that during my setup. Thanks!

Great work by the way.
